/** Get the offset of a timezone (key) in hours or [hours, minutes] */
export default {
  // Europe
  utc: "0",
  gmt: "0",
  bst: "+1",
  ist: "+1",
  wet: "0",
  west: "+1",
  cet: "+1",
  cest: "+2",
  eet: "+2",
  eest: "+3",
  msk: "+3",
  msd: "+4",
  // US/Canada
  ast: "-4",
  adt: "-3",
  est: "-5",
  edt: "-4",
  cst: "-6",
  cdt: "-5",
  mst: "-7",
  mdt: "-6",
  pst: "-8",
  pdt: "-7",
  hst: "-10",
  akst: "-9",
  akdt: "-8",
  // Australia
  aest: "+10",
  aedt: "+11",
  acst: ["+9", "30"],
  acdt: ["+10", "30"],
  awst: "+8",
};
